name: VR360
favicon: null
layout_spectrum: 0.1475225230678916
typography_spectrum: 0.9964302105363458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef0ef'
    - '#8c7b67'
    - '#00763c'
    - '#010302'
    - '#533626'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
